title: Cyber Security Journey
author: Edgar Perez
email: basdpereze9@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
#  Detailing my journey into.

github_username:  pereze03 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
